#! /usr/bin/perl
use strict;
use warnings;
use Data::Dumper;
use XML::Simple;
use Net::LDAP;
use Net::LDAP::Extension::SetPassword;
use URI;



my $parser = XML::Simple->new( KeepRoot => 1 );
my $doc = $parser->XMLin('/etc/fusiondirectory/fusiondirectory.conf');
#print Dumper $doc;

my $adminDN=$doc->{conf}{main}{location}{referral}{adminDn};
my $adminPWD=$doc->{conf}{main}{location}{referral}{adminPassword};
my $URI=$doc->{conf}{main}{location}{referral}{URI};


my $userDN=$ARGV[0];
my $userPWD=$ARGV[1];


my $ldapURI= URI->new($URI);
my $ldap_prot=$ldapURI->scheme;
my $ldap_host=$ldapURI->host;



my $ldap_cnx = Net::LDAP->new($ldap_host)
          or die "Host not found: $!";


$ldap_cnx->bind( $adminDN, password => $adminPWD );
my $mesg = $ldap_cnx->set_password(newpasswd => $userPWD, user=> $userDN );
die "error: ", $mesg->code(), ": ", $mesg->error() if ( $mesg->code() )

#$ldap_cnx->unbind();

